#
# =============================================================================
# Lite Server Monitor (LSM)
# Манифест модуля ИБП (UPS)
# =============================================================================

MODULE_NAME="ups"
MODULE_DESCRIPTION="Мониторинг ИБП через apcupsd"
MODULE_VERSION="1.0"


MODULE_DEPENDS=(
    apcupsd
)


MODULE_SERVICES=(
    lsm-ups.service
    lsm-ups.timer
)
