#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# System Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="system"
MODULE_DESCRIPTION="System Resource Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=()

MODULE_SERVICES=(
    lsm-system.service
    lsm-system.timer
)
