## Installed Files


/opt/lsm/modules/system/check_system.sh

/etc/systemd/system/lsm-system.service

/etc/systemd/system/lsm-system.timer

/etc/lsm/modules/system.conf



## Default Schedule

Every 5 minutes.
