#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Манифест модуля Docker
# -----------------------------------------------------------------------------

MODULE_NAME="docker"
MODULE_DESCRIPTION="Мониторинг демона Docker, статуса контейнеров и дискового пространства"
MODULE_VERSION="1.0"

MODULE_DEPENDS=(
    docker
)

MODULE_SERVICES=(
    lsm-docker.service
    lsm-docker.timer
)
