#!/usr/bin/env bash
# ==============================================================================
# Lite Server Monitor (LSM)
# Метаданные модуля Disk
# ==============================================================================


MODULE_ID="disk"

MODULE_NAME="Мониторинг дискового пространства"

MODULE_DESCRIPTION="Контроль свободного места на файловых системах"

MODULE_VERSION="1.0"

MODULE_CATEGORY="storage"


MODULE_DEPENDENCIES=""

MODULE_REQUIRED_PACKAGES=""


MODULE_SERVICE="lsm-disk.service"

MODULE_TIMER="lsm-disk.timer"
