#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Disk Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="disk"
MODULE_DESCRIPTION="Disk Usage Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=()

MODULE_SERVICES=(
    lsm-disk.service
    lsm-disk.timer
)

MODULE_FILES=(
    check_disk.sh
)
