#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# RAID Module Manifest
# -----------------------------------------------------------------------------

MODULE_NAME="raid"
MODULE_DESCRIPTION="Linux Software RAID Monitoring"
MODULE_VERSION="1.0"

MODULE_DEPENDS=()

MODULE_SERVICES=(
    lsm-raid.service
    lsm-raid.timer
)
