#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# RAID Configuration
# -----------------------------------------------------------------------------

#
# Enable notifications
#

NOTIFY_ON_FAILURE=true
NOTIFY_ON_RECOVERY=true

#
# Arrays to ignore (space separated)
#

IGNORE_ARRAYS=""
