#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Login Configuration
# -----------------------------------------------------------------------------

#
# Monitor SSH logins
#

MONITOR_SSH=true


#
# Monitor failed login attempts
#

MONITOR_FAILED=true


#
# Notification settings
#

NOTIFY_ON_LOGIN=true
NOTIFY_ON_FAILED=true
