#
# -----------------------------------------------------------------------------
# Lite Server Monitor (LSM)
# Fail2Ban Configuration
# -----------------------------------------------------------------------------

#
# Monitor enabled jails
#

MONITOR_JAILS=true


#
# Notification options
#

NOTIFY_ON_BAN=true
NOTIFY_ON_RECOVERY=true
